// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2_iGIXoIWbYRbtCwttcVBuqrANIWXI_s',
    appId: '1:247765788378:web:f69869d967e3b188dae7e3',
    messagingSenderId: '247765788378',
    projectId: 'mesclainvest-387a8',
    authDomain: 'mesclainvest-387a8.firebaseapp.com',
    storageBucket: 'mesclainvest-387a8.firebasestorage.app',
    measurementId: 'G-TV8BS90HB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALXE2-nOAzlVQ_nPZNqP9bvIXB1x8HcIg',
    appId: '1:247765788378:android:7065c4e7e89a2be8dae7e3',
    messagingSenderId: '247765788378',
    projectId: 'mesclainvest-387a8',
    storageBucket: 'mesclainvest-387a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDalcmI7_TMdsxvnlobgrRxXedTsLfHAVM',
    appId: '1:247765788378:ios:9fbaa03e7b08b5e7dae7e3',
    messagingSenderId: '247765788378',
    projectId: 'mesclainvest-387a8',
    storageBucket: 'mesclainvest-387a8.firebasestorage.app',
    iosBundleId: 'com.example.piIii',
  );
}
